version: "3.3"

services:
  elasticsearch:
    container_name: es-cluster
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    environment:
      - xpack.security.enabled=false
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es-net:
    driver: bridge
